#!/usr/bin/env python
from datetime import datetime

def ts2date(timestamp):
    return datetime.fromtimestamp(timestamp / 1000)

if __name__ == "__main__":
    import sys
    timestamp = int(sys.argv[1])
    print ts2date(timestamp)
